all: /home/angad/OS_ASSIGNMENTS/ASSIGNMENT-1-MODIFIVE/upload/starter/with-bonus/bin/lib_simpleloader.so

/home/angad/OS_ASSIGNMENTS/ASSIGNMENT-1-MODIFIVE/upload/starter/with-bonus/bin/lib_simpleloader.so: loader.c
	gcc -m32 -shared -o $@ $<

clean:
	-rm -f /home/angad/OS_ASSIGNMENTS/ASSIGNMENT-1-MODIFIVE/upload/starter/with-bonus/bin/lib_simpleloader.so

